# ============================================================================
# STREAMLIT SECRETS - Configuración de API Keys
# ============================================================================

# API Key de Groq para el sistema RAG educativo
# Obtén tu API key GRATIS en: https://console.groq.com/keys
GROQ_API_KEY = "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"

# API Key alternativa de Groq (backup)
GROQ_API_KEY_BACKUP = "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"

# Configuración de la aplicación
[app]
title = "Sistema de Riesgo Crediticio con RBM"
version = "1.0.0"
author = "Sistema de Física"

# Configuración del modelo RBM
[rbm]
default_n_hidden = 100
default_learning_rate = 0.01
default_n_epochs = 100
default_batch_size = 64
default_k_cd = 1

# Configuración del sistema RAG
[rag]
chunk_size = 1500
chunk_overlap = 300
top_k_results = 6
model_name = "llama-3.3-70b-versatile"
temperature = 0.3
max_tokens = 2048

# Configuración de embeddings
[embeddings]
model_name = "sentence-transformers/all-MiniLM-L6-v2"
device = "cpu"
normalize_embeddings = true